
  /comments:
    get:
     summary: Get all commentss
     tags: [comments]
     responses:
       200:
        schema:
          $ref: '#/components/schemas/comments'
 
    post:
      summary: Create comments
      tags: [comments]
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/comments'
      responses:
        201:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/comments'
 
  /comments/{id}:
    get:
      summary: Get comments by id
      tags: [comments]
      parameters:
        - in: path
          name: id
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/comments'
 
    put:
      summary: Edit comments
      tags: [comments]
      parameters:
        - in: path
          name: id
      responses:
        202:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/comments'
      requestBody:
        content:
            application/json:
              schema:
               $ref: '#/components/schemas/comments'
 
    delete:
      summary: Delete comments
      tags: [comments]
      parameters:
        - in: path
          name: id
      responses:
        202:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/comments'

  /blogs:
    get:
     summary: Get all blogss
     tags: [blogs]
     responses:
       200:
        schema:
          $ref: '#/components/schemas/blogs'
 
    post:
      summary: Create blogs
      tags: [blogs]
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/blogs'
      responses:
        201:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/blogs'
 
  /blogs/{id}:
    get:
      summary: Get blogs by id
      tags: [blogs]
      parameters:
        - in: path
          name: id
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/blogs'
 
    put:
      summary: Edit blogs
      tags: [blogs]
      parameters:
        - in: path
          name: id
      responses:
        202:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/blogs'
      requestBody:
        content:
            application/json:
              schema:
               $ref: '#/components/schemas/blogs'
 
    delete:
      summary: Delete blogs
      tags: [blogs]
      parameters:
        - in: path
          name: id
      responses:
        202:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/blogs'

  /user:
    get:
     summary: Get all users
     tags: [user]
     responses:
       200:
        schema:
          $ref: '#/components/schemas/user'
 
    post:
      summary: Create user
      tags: [user]
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/user'
      responses:
        201:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/user'
 
  /user/{id}:
    get:
      summary: Get user by id
      tags: [user]
      parameters:
        - in: path
          name: id
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/user'
 
    put:
      summary: Edit user
      tags: [user]
      parameters:
        - in: path
          name: id
      responses:
        202:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/user'
      requestBody:
        content:
            application/json:
              schema:
               $ref: '#/components/schemas/user'
 
    delete:
      summary: Delete user
      tags: [user]
      parameters:
        - in: path
          name: id
      responses:
        202:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/user'

  components:
    schemas:
  
      comments:
        type: object
        properties:
      
          id:
            type: string
          body:
            type: string
          blogs:
            type: string
          user:
            type: string
      blogs:
        type: object
        properties:
      
          id:
            type: string
          name:
            type: string
          content:
            type: string
          user:
            type: string
      user:
        type: object
        properties:
      
          id:
            type: number
          name:
            type: string
          email:
            type: string
          gender:
            type: string
          age:
            type: number
          password:
            type: string
          phone:
            type: string